### PR TITLE
Update ansible drpmachines.py to have correct syntax

### PR DESCRIPTION
**Pull request by zehicle**
Also updates the docs.
Added some handy config options (ansible_name and IP address from param)

Related to #1283 but in the preferred file location.

### CODE REVIEW

**Comment by zehicle** [comment]
includes docs for AWS too

**Comment by tombull** [comment]
In `drpmachines.py`, the line 104
`hosts = requests.get(addr + "/api/v3/machines?slim=Params&Profiles=In("+name+")",headers=Headers,auth=(user,password),verify=False)`
still doesn't work against the version of the DRP API that I have installed (latest stable version, I've not tested it against tip - so I don't know if it works against the latest version).

**Comment by tombull** [comment]
Futhermore, in that section of `drpmachines.py` - line 111-116, you're making O(n) [n=machines] against the DRP API to get information you already have stored in the variable `raw`.

**Comment by galthaus** [comment]
> In `drpmachines.py`, the line 111
> `hosts = requests.get(addr + "/api/v3/machines?slim=Params&Profiles=In("+name+")",headers=Headers,auth=(user,password),verify=False)`
> still doesn't work against the version of the DRP API that I have installed (latest stable version, I've not tested it against tip - so I don't know if it works against the latest version).

Yeah - this is TIP to take advantage of new filter operators.

**Comment by zehicle** [comment]
@tombull you are correct - it requires tip due to the In(machine)
Also, it's O(n) on profiles - generally a much smaller number.

**Pull request merged**
